server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://shiyang.wei:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: foodie-shop-dev
    password: mBw4PsjdjbarJEPc

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl